### ISSUE TITLE
SCS0016 with custom AntiForgery filter attribute like ValidateHeaderAntiForgeryTokenAttribute

### ISSUE THREAD

**Issue by melcug** [security-code-scan/security-code-scan#149]
**Environment:**
 - Version [3.3.0]
 - Branch [SCS0016]
 - Visual Studio [2019 (16.3.6)]
 - OS: [Windows]

**Description of the bug:**
Passing AntiForgeryToken in a JSON post request along wih JSON.stringify is not working so I applied the solution (creating a custom filter and passing the token to ajax request in header) provided on [https://stackoverflow.com/questions/45866060/passing-antiforgerytoken-in-a-json-post-request-along-wih-json-stringify-is-not](https://stackoverflow.com/questions/45866060/passing-antiforgerytoken-in-a-json-post-request-along-wih-json-stringify-is-not).

SCS0016 is still reported even I added [ValidateHeaderAntiForgeryToken] attribute to my methods.

Now, is difficult to know to which of the methods with [HttpPost] attribute is missing the attribute [ValidateHeaderAntiForgeryToken], because all are reported.

**Comment by JarLob** [comment]
Could you attach a solution with code example?

**Comment by melcug** [comment]
I attached a sample project that includes a new filter called ValidateHeaderAntiForgeryToken that validates the token provided in the headers section of the post request (see below pictures).
![Uploading Token.png…]()
As you can see,  the method Login has [HttpPost] and custom [ValidateHeaderAntiForgeryToken] attributes, but not the standard [ValidateAntiForgeryToken] attribute.
![Uploading SCS0016.png…]()

**Comment by JarLob** [comment]
Thanks for PoC. So I misunderstood the question. If you have a **custom** antiCSRF attribute you need a custom configuration entry for it. If you make the configuration wrong you may get warnings on every single method and class in the solution. This is explain your "is difficult to know ... because all are reported". If your configuration is correct you still may see warnings from default MVC CSRF analyzer. You need to set your config entry name to `ASP.NET MVC` to override it. See complete example below:
```yml
CsrfProtection:
  - Name: ASP.NET MVC
    AntiCsrfAttributes:
      - Name: System.Web.Mvc.ValidateAntiForgeryTokenAttribute
      - Name: AntiForgeryTest.Folders.ValidateHeaderAntiForgeryTokenAttribute
    Class:
      Name:
        - System.Web.Mvc.Controller
      Attributes:
        Exclude:
          - Name: System.Web.Mvc.AllowAnonymousAttribute
    Method:
      Attributes:
        Include:
          - Name: System.Web.Mvc.HttpPostAttribute
          - Name: System.Web.Mvc.HttpPutAttribute
          - Name: System.Web.Mvc.HttpDeleteAttribute
          - Name: System.Web.Mvc.HttpPatchAttribute
        Exclude:
          - Name: System.Web.Mvc.NonActionAttribute
          - Name: System.Web.Mvc.AllowAnonymousAttribute
```

**Comment by JarLob** [comment]
Correction, no need to copy/paste all entries from `ASP.NET MVC`. The example below is simply merged into existing rules:
```yml
CsrfProtection:
  - Name: ASP.NET MVC
    AntiCsrfAttributes:
      - Name: AntiForgeryTest.Folders.ValidateHeaderAntiForgeryTokenAttribute
```

**Comment by melcug** [comment]
Please excuse my ignorance, but what is the path of the default MVC CSRF analyzer config file that I "need to set your config entry name to ASP.NET MVC to override it. "?

Thanks in advance.

**Comment by melcug** [comment]
I found the documentation about the config file and now I have another issue (Version is missing or corrupted in the project configuration file ...):

![Config](https://user-images.githubusercontent.com/8708178/72383443-278b1c80-3724-11ea-97b1-73a4f3a57565.png)

**Comment by JarLob** [comment]
Refer to the https://security-code-scan.github.io/#ExternalConfigurationFiles
You need a version entry if using config per project (not needed if config is per user), like:
```yml
Version: 2.1

CsrfProtection:
  - Name: ASP.NET Core MVC
    AntiCsrfAttributes:
      - Name: MyNamespace.MyAntiCsrfAttribute
```
