### ISSUE TITLE
SQL injection detection

### ISSUE THREAD

**Issue by accent** [security-code-scan/security-code-scan#150]
I created new project (.NET Core 3.1, API) with Entity Framework Core 3.1.1

The first line below was not identified as potential SQL injection, however the second one was properly identified.

`dbContext.Books.FromSqlRaw("SELECT * FROM Books where BookId = " + bookId);
dbContext.Books.FromSql("SELECT * FROM Books where BookId = " + bookId);`

string bookId is parameter of HTTP GET action.

Even in Microsoft's documentation, there is a note that passing concatenated string is invalid approach.
https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

Is that expected behaviour or a bug?

**Comment by JarLob** [comment]
Thanks, for the specific issue you may add the following config entry, although I have added more sinks:
```yml
  RelationalQueryableExtensions_FromSqlRaw:
    Namespace: Microsoft.EntityFrameworkCore
    ClassName: RelationalQueryableExtensions
    Name: FromSqlRaw
    Method:
      InjectableArguments: [SCS0035: 1]
```
