### ISSUE TITLE
nHibernate SQL Injection Not Detected

### ISSUE THREAD

**Issue by indy-singh** [security-code-scan/security-code-scan#151]
**Environment (please complete the following information):**
- Version: `<package id="SecurityCodeScan.VS2017" version="3.4.0" targetFramework="net472" developmentDependency="true" />`
 - Visual Studio: `Microsoft Visual Studio Professional 2017 Version 15.9.12`
 - OS: `Microsoft Windows Server 2019 Standard 10.0.17763 N/A Build 17763`

**Describe the bug**
I would expect the repo to fail the build.

**Repro**
```csharp
using(var session = _database.OpenSession())
using(var transaction = session.BeginTransaction(IsolationLevel.ReadCommitted))
{
	session.CreateSQLQuery("UPDATE organisation.user SET active = false WHERE username = " + username + " ; ")
		.ExecuteUpdate();
	transaction.Commit();
}
```

I followed the example from https://github.com/security-code-scan/security-code-scan/issues/150 but I can't get it to fail the build at all.

My `SecurityCodeScan.config.yml` which is setup as described [here](https://security-code-scan.github.io/#ExternalConfigurationFiles)

```yaml
Version: 2.1

RelationalQueryableExtensions_FromSqlRaw:
    Namespace: NHibernate
    ClassName: SessionImpl
    Name: CreateSQLQuery
    Method:
      InjectableArguments: [SCS0035: 1]
```

```yaml
Version: 2.1

RelationalQueryableExtensions_FromSqlRaw:
    Namespace: NHibernate.Impl
    ClassName: SessionImpl
    Name: CreateSQLQuery
    Method:
      InjectableArguments: [SCS0035: 1]
```

Any ideas? I've tried several different YAML configs, but nothing works.

Thanks,
Indy

**Comment by JarLob** [comment]
Try adding `AuditMode: true` to the config. I might be the `username` is not tainted.

**Comment by indy-singh** [comment]
@JarLob That didn't work either. It flagged up some other stuff, so I know `AuditMode: true` is doing something. I'm sure my configuration file is incorrect somehow.

**Comment by JarLob** [comment]
1. You don't need to repeat `Version: 2.1`.
2. I see your sink is not under `Behavior:` section.
3. Argument indices are zero based, i.e. if vulnerable argument is the first one it must be 0.
4. I can only guess which method call you are trying to catch. Make sure namespace, class and method names are correct. For https://github.com/nhibernate/nhibernate-core/blob/c8b9ae6e7b4b839b21b22671e47adbba0707f0ad/src/NHibernate/Impl/AbstractSessionImpl.cs that would be:
```yml
Version: 2.1

Behavior:
  AnythingButUnique:
    Namespace: NHibernate.Impl
    ClassName: AbstractSessionImpl
    Name: CreateSQLQuery
    Method:
      InjectableArguments: [SCS0035: 0]
```

**Comment by indy-singh** [comment]
Ah okay! Can't try this now until Wednesday. Feel free to close this issue,
and I'll reopen if necessary.

Thanks,
Indy

**Comment by indy-singh** [comment]
Managed to get near a computer; this works!

```yaml
Version: 2.1

AuditMode: true

Behavior:
  AnythingButUnique:
    Namespace: NHibernate
    ClassName: ISession
    Name: CreateSQLQuery
    Method:
      InjectableArguments: [SCS0035: 0]
```

Thanks for your guidance @JarLob . There are a couple of other sinks that I want to experiment with (Npgsql driver and Cassandra driver). Are you open to including all three of these by default into SCS? Happy to put together a PR next week if so.

Indy

**Comment by JarLob** [comment]
Yes, sure. Test it with local config and I'll be happy to include them into default one.

**Comment by indy-singh** [comment]
Think I've got a complete list:-

```yaml
Version: 2.1

AuditMode: true

Behavior:
  NHIB1:
    Namespace: NHibernate
    ClassName: ISession
    Name: CreateSQLQuery
    Method:
      ArgTypes: (System.String)
      InjectableArguments: [SCS0035: 0]

  CAS1:
    Namespace: Cassandra
    ClassName: ISession
    Name: Execute
    Method:
      ArgTypes: (System.String)
      InjectableArguments: [SCS0035: 0]
      
  CAS2:
    Namespace: Cassandra
    ClassName: ISession
    Name: Execute
    Method:
      ArgTypes: (System.String, System.Int32)
      InjectableArguments: [SCS0035: 0]

  CAS3:
    Namespace: Cassandra
    ClassName: ISession
    Name: Execute
    Method:
      ArgTypes: (System.String, Cassandra.ConsistencyLevel)
      InjectableArguments: [SCS0035: 0]

  NPG1:
    Namespace: Npgsql
    ClassName: NpgsqlCommand
    Name: .ctor
    Method:
      ArgTypes: (System.String)
      InjectableArguments: [SCS0035: 0]

  NPG2:
    Namespace: Npgsql
    ClassName: NpgsqlCommand
    Name: .ctor
    Method:
      ArgTypes: (System.String, Npgsql.NpgsqlConnection)
      InjectableArguments: [SCS0035: 0]

  NPG3:
    Namespace: Npgsql
    ClassName: NpgsqlCommand
    Name: .ctor
    Method:
      ArgTypes: (System.String, Npgsql.NpgsqlConnection, Npgsql.NpgsqlTransaction)
      InjectableArguments: [SCS0035: 0]

  NPG4:
    Namespace: Npgsql
    ClassName: NpgsqlCommand
    Name: CommandText
    Field:
      Injectable: SCS0035
```

I'm not sure about using `SCS0035` - is it best to create new error codes and attach them to the respective ones correctly?

Indy
