### ISSUE TITLE
System.Data.SqlClient.SqlCommand constructor doesn't report SQL Injection

### ISSUE THREAD

**Issue by joseph-kaainoa** [security-code-scan/security-code-scan#157]
**Environment:**
 - Version 3.3.5
 - Branch SCS  
 - Visual Studio 2017 (15.9.21)
 - OS: Win10 Version 10.0.16299.1747

**Bug Description**
I was expecting a warning on SCS0026, however no warning was generated.  I thought maybe it was similar to #150, but when I looked in the Main.yml, it does have a listing for the SqlCommand constructor:
``` YML
  sqlcommand_constructor:
    Namespace: System.Data.SqlClient
    ClassName: SqlCommand
    Name: .ctor
    Method:
      InjectableArguments: [SCS0026: 0]
```

**Repro**
``` C#
string connString = "<CONNECTION>";
using (SqlConnection conn = new SqlConnection(connString))
{
	string name = "<VALUE>";
	string queryString = "SELECT TOP 10 * FROM <TABLE_NAME> WHERE Name LIKE '%" + name + "%'";
	SqlCommand command = new SqlCommand(queryString, conn);
	command.Connection.Open();
	using (SqlDataReader reader = command.ExecuteReader())
	{
		while (reader.Read())
		{
			Console.WriteLine(String.Format("{0}, {1}",
				reader[0], reader[1]));
		}
	}
}
```
