### ISSUE TITLE
How to define safe methods/sanitizers in custom configuration

### ISSUE THREAD

**Issue by MigueZS** [security-code-scan/security-code-scan#206]
Tried to upgrade to SCS for VS2019 5.1.0 into an .NET framework 4.6 solution which already had the 3.5.4 with the old configuration working. It is being hard to translate some rules just looking at the samples in the configuration file of the project.

I did a small test with the following code in a new separated console application:

```cs
using System.Data.SqlClient;

namespace SCSConfigTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var someObject = new SomeNamespace.SomeClass();
            var command1 = new SqlCommand(someObject.Sql);
            var command2 = new SqlCommand(someObject.GetSql());
            var command3 = new SqlCommand(SomeNamespace.SomeClass.StaticGetSql());
        }
    }
}


namespace SomeNamespace
{
    public class SomeClass
    {
        public string Sql { get; set; }

        public string GetSql() => string.Empty;
        public static string StaticGetSql() => string.Empty;
    }
}
```
It worked and is showing 3 warnings for the 3 SqlCommands above. What is the configuration for marking those methods as safe like in the previous version?

Tried the following for the methods, but the errors are still being shown and no clue about the property.

```yaml
Version: 3.1
ReportAnalysisCompletion: false
AuditMode: true

Sanitizers:

  - Type: SomeNamespace.SomeClass
    TaintTypes:
      - SCS0002
    Methods:
      - Name: GetSQL
      - Name: StaticGetSql

```

**Comment by JarLob** [comment]
Hi, did you give it a try without the `AuditMode`?
The taint tracking has changed significantly between 3.x and 5.x. In pre 5.x the AuditMode was tainting any function input as untrusted. Effectively it was highlighting all possible sinks for manual review. Some obvious safe cases were filtered out. This explains why sanitizers were working for you. In 5.x the idea is the same - highlight all possible sinks, but it is infeasible for internal implementation to taint all possible inputs. Thus sanitizers are not used in the AuditMode. It filters out only constants.

If you disable the audit mode it won't show you any warning because there is simply no untrusted input. You can add
```yaml
TaintEntryPoints:
  SCSConfigTest.Program:
    Method:
      Name: Main
```
to get taint tracking. Then you need to actually use the `args`.
In your real application it may work out of the box if it is a web app or you may add `TaintEntryPoints:` and `TaintSources:` specific to your architecture.

**Comment by MigueZS** [comment]
Thank you for your quick response, so I changed my simple example to

```cs
using System.Data.SqlClient;

namespace SCSConfigTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var someObject = new SomeNamespace.SomeClass();
            var command1 = new SqlCommand(someObject.Sql);
            var command2 = new SqlCommand(someObject.GetSql(args[0]));
            var command3 = new SqlCommand(SomeNamespace.SomeClass.StaticGetSql(args[0]));
            var command4 = new SqlCommand(args[0]);
            var command5 = (new SomeNamespace.SomeOtherClass()).GetCommand(args[0]);
        }
    }
}


namespace SomeNamespace
{
    public class SomeClass
    {
        public string Sql { get; set; }

        public string GetSql(string input) => string.Empty;
        public static string StaticGetSql(string input) => string.Empty;
    }

    public class SomeOtherClass
    {
        public SqlCommand GetCommand(string sql) => new SqlCommand(sql);
    }
}
```

```yaml
Version: 3.1
ReportAnalysisCompletion: false
AuditMode: false

TaintEntryPoints:
  SCSConfigTest.Program:
    Method:
      Name: Main

#Sanitizers:

  #- Type: SomeNamespace.SomeClass
  #  TaintTypes:
  #    - SCS0002
  #  Methods:
  #    - Name: GetSQL
  #    - Name: StaticGetSql
```

So, before checking the sanitizers I commented them out just to test the taint source is working. The analyzer is running but is only complaining about the last one (command4).

According to what I have understood without the audit mode, do we have to configure every class, for example:
-  SomeOtherClass as a taint entry point in the configuration to get the warning in the "string sql" parameter when it is used in the new SqlCommand(sql)?
-  In the case of the Sql property of SomeClass to make the warning throw when it is used in the main method when the SqlCommand is created, should it be a declared as a taint source?
- In the case of the SomeOtherClass.GetCommand to throw a warning when it is receiving the args parameter should be declared as a sink?

The config that showed all the warnings in this case is

```yaml
Version: 3.1
ReportAnalysisCompletion: false
AuditMode: false

TaintEntryPoints:
  SCSConfigTest.Program:
    Method:
      Name: Main

  SomeNamespace.SomeOtherClass:
    Method:
      Name: GetCommand

TaintSources:

  - Type: SomeNamespace.SomeClass
    Properties:
      - Sql

Sinks:

  - Type: SomeNamespace.SomeOtherClass
    TaintTypes:
      - SCS0002
    Methods:
      - Name: GetCommand
        Arguments:
        - sql
```

I know that a good architecture will allow to define less configuration, but for old projects that are unlikely to change in a short term we use the analyzers in audit mode to throw whatever they find on lower layers, helping us to configure sinks and sanitizers where appropriate (or changing the code because it was wrong) until we reach the top layers.
