### ISSUE TITLE
Running security-code-scan on Linux docker with GitLab

### ISSUE THREAD

**Issue by dennys** [security-code-scan/security-code-scan#236]
I reference https://github.com/security-code-scan/security-code-scan/issues/226 to build and scan dotnet code on GitLab and the GitLab runner runs on a docker. But it shows the error message

`Msbuild failed when processing the file '/builds/.../xxx.csproj' with message: /usr/share/dotnet/sdk/5.0.404/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets: (241, 5): Package Microsoft.CodeAnalysis.Analyzers, version 2.9.4 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.`

And then I add a `dotnet restore` and it works, the following is the .gitlab-ci.yml for your reference.

```
stages:
    - security-code-scan

security-code-scan:
    stage: security-code-scan
    tags:
        - docker
    image: mcr.microsoft.com/dotnet/sdk:5.0
    script:
        - dotnet restore
        - dotnet tool install --global security-scan
        - $HOME/.dotnet/tools/security-scan example.sln --excl-proj=**/*Test*/** --export=report/out.sarif
    artifacts:
        paths:
            - ./report
```
